IMPORTING LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

DEFINING DATASET

In [ ]:
df = pd.read_csv('/content/application_record.csv')
df1 = pd.read_csv('/content/credit_record.csv')

READING & ANALYSING DATASET

In [ ]:
nature = []
for i in df1['STATUS']:
  if i == "X":
    nature.append(0)
  elif i == "C" or i == "0" or i == "1" or i == "2":
    nature.append(1)
  else:
    nature.append(0)

In [ ]:
df1['COUSTOMER_NATURE'] = nature

MERGING DATASET

In [ ]:
final_data = df.merge(df1)

EXPLORATORY DATA ANALYISIS (CLEANING DATASET)

In [ ]:
final_data = final_data.drop("NAME_FAMILY_STATUS",axis= 1)
final_data = final_data.drop("FLAG_MOBIL",axis= 1)
final_data = final_data.drop("FLAG_WORK_PHONE",axis= 1)
final_data = final_data.drop("FLAG_PHONE",axis= 1)
final_data = final_data.drop("FLAG_EMAIL",axis= 1)
final_data = final_data.drop("MONTHS_BALANCE",axis= 1)
final_data = final_data.drop("STATUS",axis= 1)

In [ ]:
final_data.info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 777715 entries, 0 to 777714
Data columns (total 14 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   ID                   777715 non-null  int64  
 1   CODE_GENDER          777715 non-null  object 
 2   FLAG_OWN_CAR         777715 non-null  object 
 3   FLAG_OWN_REALTY      777715 non-null  object 
 4   CNT_CHILDREN         777715 non-null  int64  
 5   AMT_INCOME_TOTAL     777715 non-null  float64
 6   NAME_INCOME_TYPE     777715 non-null  object 
 7   NAME_EDUCATION_TYPE  777715 non-null  object 
 8   NAME_HOUSING_TYPE    777715 non-null  object 
 9   DAYS_BIRTH           777715 non-null  int64  
 10  DAYS_EMPLOYED        777715 non-null  int64  
 11  OCCUPATION_TYPE      537667 non-null  object 
 12  CNT_FAM_MEMBERS      777715 non-null  int64  
 13  COUSTOMER_NATURE     777715 non-null  int64  
dtypes: float64(1), int64(6), object(7)
memory usage: 89.0+ MB


FEATURE ENGINEERING (ENCODING FEATURES)

In [ ]:
final_data["CODE_GENDER"] = final_data["CODE_GENDER"].map({"F":0, "M":1})

In [ ]:
final_data["FLAG_OWN_CAR"] = pd.get_dummies(final_data["FLAG_OWN_CAR"],drop_first = 1)


In [ ]:
final_data["FLAG_OWN_REALTY"] = pd.get_dummies(final_data["FLAG_OWN_REALTY"],drop_first = 1)

In [ ]:
final_data["NAME_INCOME_TYPE"] = final_data["NAME_INCOME_TYPE"].map({"Working":0, "Commercial associate":1, "Pensioner":2,"State servant":3,"Student":4})

In [ ]:
final_data["NAME_EDUCATION_TYPE"] = final_data["NAME_EDUCATION_TYPE"].map({"Higher education":0, "Secondary / secondary special":1, "Incomplete higher":2,"Lower secondary":3,"Academic degree":4})


In [ ]:
final_data["NAME_HOUSING_TYPE"] = final_data["NAME_HOUSING_TYPE"].map({"Rented apartment":0, "House / apartment":1, "Municipal apartment":2,"With parents":3,"Co-op apartment":4,"Office apartment":5})


In [ ]:
def impute_nan(final_data,variable):
    final_data[variable+"NEW"]=np.where(final_data[variable].isnull(),"Missing",final_data[variable])


In [ ]:
for feature in ['OCCUPATION_TYPE']:
    impute_nan(final_data,feature)

In [ ]:
final_data["OCCUPATION_TYPENEW"].unique()

array(['Missing', 'Security staff', 'Sales staff', 'Accountants',
       'Laborers', 'Managers', 'Drivers', 'Core staff',
       'High skill tech staff', 'Cleaning staff', 'Private service staff',
       'Cooking staff', 'Low-skill Laborers', 'Medicine staff',
       'Secretaries', 'Waiters/barmen staff', 'HR staff', 'Realty agents',
       'IT staff'], dtype=object)

In [ ]:
final_data["OCCUPATION_TYPENEW"] = final_data["OCCUPATION_TYPENEW"].map({"Missing":0, "Security staff":1, "Sales staff":2,"Accountants":3,"Laborers":4,"Managers":5,"Drivers":6,"Core staff":7,"High skill tech staff":8,"Cleaning staff":9,"Private service staff":10,"Cooking staff":11,"Low-skill Laborers":12,"Medicine staff":13,"Secretaries":14,"Waiters/barmen staff":15,"HR staff":16,"Realty agents":17,"IT staff":18})


In [ ]:
final_data["OCCUPATION_TYPENEW"].unique()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [ ]:
final_data = final_data.drop("OCCUPATION_TYPE",axis= 1)


DROPPING DUPLICATE DATA

In [ ]:
final_data=final_data.drop_duplicates(subset = "ID")


In [ ]:
final_data.info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 36457 entries, 0 to 777701
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   ID                   36457 non-null  int64  
 1   CODE_GENDER          36457 non-null  int64  
 2   FLAG_OWN_CAR         36457 non-null  uint8  
 3   FLAG_OWN_REALTY      36457 non-null  uint8  
 4   CNT_CHILDREN         36457 non-null  int64  
 5   AMT_INCOME_TOTAL     36457 non-null  float64
 6   NAME_INCOME_TYPE     36457 non-null  int64  
 7   NAME_EDUCATION_TYPE  36457 non-null  int64  
 8   NAME_HOUSING_TYPE    36457 non-null  int64  
 9   DAYS_BIRTH           36457 non-null  int64  
 10  DAYS_EMPLOYED        36457 non-null  int64  
 11  CNT_FAM_MEMBERS      36457 non-null  int64  
 12  COUSTOMER_NATURE     36457 non-null  int64  
 13  OCCUPATION_TYPENEW   36457 non-null  int64  
dtypes: float64(1), int64(11), uint8(2)
memory usage: 3.7 MB


In [ ]:
final_data["COUSTOMER_NATURE1"]=final_data["COUSTOMER_NATURE"]



In [ ]:
final_data = final_data.drop("COUSTOMER_NATURE",axis= 1)


EXPORTING FINAL DATA AFTER EDA & FEATURE ENGINEERING

In [ ]:
final_data.to_excel("final_eda3.xlsx")


In [ ]:
df = pd.read_excel('final_eda3.xlsx')


In [ ]:
x = df.iloc[:,2:14]
y = df.iloc[:,14]

SPLITTING DATA INTO TRAINING & TEST SET

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size= 0.2,random_state = 51)

IMPLEMENTING SVC

In [ ]:
from sklearn.svm import SVC
classifiersv = SVC(kernel = "sigmoid",random_state = 52)
classifiersv.fit(x_train,y_train)

SVC(kernel='sigmoid', random_state=52)

In [ ]:
y_pred = classifiersv.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6213658804168952

BY USING CROSS VALIDATION (SVC)

In [ ]:
from sklearn.model_selection import cross_val_score
cv_score_svc = cross_val_score(SVC(kernel="rbf"),x,y,cv=5)

In [ ]:
cv_score_svc

array([0.73244652, 0.73230938, 0.73240982, 0.73240982, 0.73240982])

IMPLEMENTING KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifierknn= KNeighborsClassifier(n_neighbors=5, metric="minkowski",p=2)
classifierknn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred= classifierknn.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7439659901261657

BY USING CROSS VALIDATION (KNN)

In [ ]:
from sklearn.model_selection import cross_val_score
cv_score_knn = cross_val_score(KNeighborsClassifier(n_neighbors=5, metric="minkowski",p=3),x,y,cv=4)


In [ ]:
cv_score_knn

array([0.63960505, 0.63364055, 0.63210445, 0.65426816])

IMPLEMENTING LOGISTIC REGRESSION

In [ ]:
y_pred= classifierlr.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7299780581459133

BY USING CROSS VALIDATION (LOGISTIC REGRESSION)

In [ ]:
from sklearn.model_selection import cross_val_score
cv_score_lr = cross_val_score(LogisticRegression(random_state=56),x,y,cv=4)

In [ ]:
cv_score_lr


array([0.73241909, 0.73238973, 0.73238973, 0.73238973])

IMPLEMENTING DECISION TREE

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifierdt = DecisionTreeClassifier(criterion="entropy",random_state=56)
classifierdt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=56)

In [ ]:
y_pred= classifierdt.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)


0.7534284147010423

BY USING CROSS VALIDATION (DECISION TREE)

In [ ]:
from sklearn.model_selection import cross_val_score
cv_score_dt = cross_val_score(DecisionTreeClassifier(criterion="entropy",random_state=56),x,y,cv=4)


In [ ]:
cv_score_dt

array([0.58178826, 0.60434496, 0.593702  , 0.60390608])

In [ ]:
a=classifierknn.predict([[1,1,1,0,427500,0,0,0,-12005,-4542,2,0]])
if a==1:
  print("we can approve the credit card to this application")
else:
  print("we can't approve the credit card to this application")

We can approve the credit card to this application


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [ ]:
!pip install tpot

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.4/87.4 kB 2.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.4/135.4 kB 10.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for stopit: filename=stopit-1.1.2-py3-none-any.whl size=11937 sha256=db935b7f970a66eabf652b02090255c08605001d3e02121fc63789d1e2e5d6ec
  Stored in directory: /root/.cache/pip/wheels/af/f9/87/bf5b3d565c2a007b4dae9d8142dccc85a9f164e517062dd519
Successfully built stopit


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from tpot import TPOTClassifier

In [ ]:
df = pd.read_excel('final_eda3.xlsx')

In [ ]:
X = df.iloc[:,2:14]
y = df.iloc[:,14]

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36457 entries, 0 to 36456
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   CODE_GENDER          36457 non-null  int64  
 1   FLAG_OWN_CAR         36457 non-null  int64  
 2   FLAG_OWN_REALTY      36457 non-null  int64  
 3   CNT_CHILDREN         36457 non-null  int64  
 4   AMT_INCOME_TOTAL     36457 non-null  float64
 5   NAME_INCOME_TYPE     36457 non-null  int64  
 6   NAME_EDUCATION_TYPE  36457 non-null  int64  
 7   NAME_HOUSING_TYPE    36457 non-null  int64  
 8   DAYS_BIRTH           36457 non-null  int64  
 9   DAYS_EMPLOYED        36457 non-null  int64  
 10  CNT_FAM_MEMBERS      36457 non-null  int64  
 11  OCCUPATION_TYPENEW   36457 non-null  int64  
dtypes: float64(1), int64(11)
memory usage: 3.3 MB


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.20,
                                                    random_state=2021)

In [ ]:
pipeline_optimizer = TPOTClassifier()
pipeline_optimizer = TPOTClassifier(generations=5, population_size=20, cv=5,
                                    random_state=42, verbosity=2)
pipeline_optimizer.fit(X_train, y_train)

Optimization Progress:   0%|          | 0/120 [00:00<?, ?pipeline/s]



TPOT closed during evaluation in one generation.


TPOT closed prematurely. Will use the current best pipeline.

Best pipeline: GaussianNB(input_matrix)


TPOTClassifier(generations=5, population_size=20, random_state=42, verbosity=2)